version: '3'

services: 
    database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: abcd@1234
        ports: 
            - 3306:3306
